spring.application.name=api-monolito

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/tcc_bes_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JDBC Configuration
spring.jdbc.template.query-timeout=30

